on:
  push:
    branches:
      - apaaja # sesuai kan dengan branch repo mu
  schedule:
    - cron: '0 */5 * * *'  # Setiap 5 jam

concurrency:
  group: 'whatsapp-bot'
  cancel-in-progress: true

jobs:
  run-whatsapp-bot:
    runs-on: ubuntu-latest
